### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by AndreDutraDCC** [Ferase/dnh-ph3sx#7]
I'm not sure if this project is still active, but if it is, how do I install the extension? As of today, no extension is available in vscode marketplace under the name "dnh", neither the original by Serajnik nor this one. I've reached out Serajnik about it and they told me to look up this fork. Would there be a .vsix file available somewhere so we can install the extension locally?

**Comment by Ferase** [comment]
Hello! Yes, the extension is available in VSIX format through the releases page:
https://github.com/Ferase/dnh-ph3sx/releases

This project is technically alive, but it's at a standstill right now because there are some new functions in ph3sx that don't have proper documentation yet.

Let me know if you have any issues installing the VSIX file!
